baseURL = "https://gerard.paligot.com"
languageCode = "en-us"
title = "Gérard Paligot"
theme = "hugo-theme-m10c"
disableKinds = ["taxonomy", "term"]

[params]
  author = "Gérard Paligot"
  description = "Father and husband, Senior Staff Engineer @Decathlon, co-organisator LAUG and FRAUG, Kotlin Lover, Disney Fan!"
  avatar = "avatar002.jpg"
  [[params.social]]
    icon = "linkedin"
    name = "gpaligot"
    url = "https://www.linkedin.com/in/gpaligot/"
  [[params.social]]
    icon = "brand-github"
    name = "GerardPaligot"
    url = "https://github.com/GerardPaligot"
  [[params.social]]
    icon = "brand-bluesky"
    name = "@paligot.com"
    url = "https://bsky.app/profile/paligot.com"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"

  [[menu.main]]
    identifier = "speaking"
    name = "Speaking"
    url = "/speaking/"

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
